### ISSUE TITLE
Support jQuery 1.8+

### ISSUE THREAD

**Issue by devinrhode2** [occ/TraceKit#3]
TraceKit supports finding exceptions in jQuery ajax callbacks, namely `.complete`, `.success`, and `.error` but these are deprecated and will be removed in 1.9 in trade for `.done`, `.fail`, and `.always`

Furthermore, it looks like this code could be based on an array of these method names, instead of duplicated code among 3-6 blocks

**Comment by niemyjski** [comment]
I'm closing this issue. If this is still an issue please let me know by opening an issue in the root repository: https://github.com/csnover/TraceKit
