### ISSUE TITLE
Use fewer global dots in Regular Expressions

### ISSUE THREAD

**Issue by devinrhode2** [occ/TraceKit#4]
Pretty self explanatory. I have no exact bugs, but jshint complains about it and it would be good to avoid using `.`

This can be as simple as converting most dots to the explicit negated newline class: `[^\n]` and other more-specific patterns where relevant.

We can then flip on the jshint option for regex: true, which is commented out right now

**Comment by niemyjski** [comment]
@devinrhode2 I'm helping maintain TraceKit upstream.. If you want to recreate this issue in the master (https://github.com/csnover/TraceKit). Could you please create a pull request for this.

**Comment by niemyjski** [comment]
I've updated the regex's in the latest build. Can you please let me know if this is still an issue.
