### ISSUE TITLE
Support Chrome Canary's window.onerror fix (adds colno, error)

### ISSUE THREAD

**Issue by ssafejava** [occ/TraceKit#48]
See this [writeup about the change](https://mikewest.org/2013/08/debugging-runtime-errors-with-window-onerror) and the [Blink bug report](https://code.google.com/p/chromium/issues/detail?id=147127).

This is good news! The 4th and 5th parameters (colno, error) are now part of the living HTML5 spec and have a good chance of making it into Firefox & others. It is now live in Canary and will trickle down to the dev & stable releases in the next weeks.

If no one is available to tackle this I can start working on a patch. If we detect support for these attributes, we could finally drop the setTimeout/setInterval wrappers & so on in those browsers.

**Comment by niemyjski** [comment]
We now support this in the latest release: https://github.com/csnover/TraceKit
