### ISSUE TITLE
Huge size of errorReport.stack[].context

### ISSUE THREAD

**Issue by mahboob-awan** [occ/TraceKit#50]
Hi,

If JavaScript files are minified then `errorReport.stack[].context` return almost complete javascript file. So what will be the right solution to avoid `context` for server-side logging?

**Comment by niemyjski** [comment]
@mahboob-awan would you mind logging this here: https://github.com/csnover/TraceKit as this is actively maintained now.. I think we should limit the line to xx characters so a whole script isn't collected.
