### ISSUE TITLE
firefox .columnNumber support?

### ISSUE THREAD

**Issue by acthp** [occ/TraceKit#53]
I see in the code comments that an "unreliable column number" is supported in firefox, though it looks like it attempts this by doing a string match. I guess that's the unreliable part. With compressed code, I've never seen it return a value. Why not use error.columnNumber, which reports the column number of the first frame?

**Comment by niemyjski** [comment]
@acthpI'm helping maintain TraceKit upstream.. If you want to recreate this issue in the master (https://github.com/csnover/TraceKit) That would be greatly appreciated.

**Comment by niemyjski** [comment]
This now happens in the latest release on https://github.com/csnover/TraceKit

**Comment by devinrhode2** [comment]
Nice job Blake!


-Devin <http://zerply.com/DevinRhode2>
<http://zerply.com/devinrhode2>
