### ISSUE TITLE
Protocol relative paths in Chrome

### ISSUE THREAD

**Issue by rakeshpai** [occ/TraceKit#64]
I came across a stack frame today, from Chrome, that had protocol-relative paths:
```
TypeError: Cannot read property 'describe' of undefined
    at Object.eval (//example.com/views/data/manager/view.js:2:19866)
    at j (https://example.com/javascript/jquery-2.1.1.min.js:2:26860)
    at Object.k.fireWith [as resolveWith] (https://exmaple.com/javascript/jquery-2.1.1.min.js:2:27673)
```

The first stack frame has a protocol-relative path. Not sure how it got there, but maybe we should parse this correctly regardless. However, currently the URL isn't being parsed correctly, because it seems to require a `file|http|https` [in the regex](https://github.com/occ/TraceKit/blob/master/tracekit.js#L621).

My regex-foo isn't awesome, or I'd have sent you a pull request. Let me know if there's anything I can do to help.

**Comment by niemyjski** [comment]
@rakeshpai , I'm helping maintain TraceKit upstream.. If you want to recreate all the issues / pull requests in the master (https://github.com/csnover/TraceKit) I'll participate in the discussion and merge them in!

**Comment by niemyjski** [comment]
We now support this in the latest release: https://github.com/csnover/TraceKit
