### ISSUE TITLE
Is TraceKit dead?

### ISSUE THREAD

**Issue by niemyjski** [occ/TraceKit#70]
I am tempted to use this in our oss project but I see there is very little activity, no comments on recent issues, no recent commits or releases. Is anyone maintaining this project?

**Comment by Incognito** [comment]
csnover is open to giving ownership over to someone else. To be honest I was going to take this over, except I changed jobs and no longer need to use this.

That being said, I have this in production elsewhere and found it useful.

As far as I know, this is the best project for this need.

**Comment by niemyjski** [comment]
@Incognito  Do you know who owns the npm source?

**Comment by Incognito** [comment]
@niemyjski Looks like you've taken care of it already. Thank you so much for doing this!

**Comment by niemyjski** [comment]
No problem :)
